pipeline{
    agent{
        label 'node-jenkins'
    }
    
    environment {
        docker_username = "pavankalyan524"
    }
    
    stages{
        
        stage("Checkout "){
            steps{
                git branch: 'master', url: "https://github.com/pavankalyan524/Python-Flask.git"
            }
        }
        stage("Docker Installation"){
            steps{
                sh '''
                sudo apt install docker.io -y
                whoami 
                '''
                
            }
            
        }
        stage("Building Docker Image"){
            steps{
                sh '''
                cd "$WORKSPACE/production/"
                docker build -t testing-image .
                docker run -d --name python-flask-container -p 8000:8000 testing-image
                '''
            }
        }
        stage("Pushing Image on to Hub"){
            steps{
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: 'https://index.docker.io/v1/']){
                sh '''
                docker tag testing-image $docker_username/testing-jenkins:version1
                docker image push $docker_username/testing-jenkins:version1
                '''
                }
            }
        }
        stage("After Pushing"){
            steps{
                echo "Image Pushed To Hub Successfully.."
            }
        }
    }
}
